import fire


class Evaluator(object):
    """A simple calculator class."""

    def help(self):
        print("""Evaluation of models using specific method
        usage:
        \tpython es.py evaluation --real=realdata --fake=fakedata --div=kld **kargs=kargs
        args:
        \treal: molecules from the database (SMILES list file)
        \tfake: molecules generated by the model (SMILES list file)
        \tdiv: evaluation method (kld, jsd, kdd etc.) 
        \t**kargs: arguments
        """)


if __name__ == '__main__':
    fire.Fire(Evaluator)